######################## default configuration ####################
baseURL = "https://jonca.org"
title = "JoncaDotOrg | Jacek Jonca-Jasinski"
theme = "somrat"
# disable language
disableLanguages = [] # desable language from here

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/fonts/fonts.css"
[[params.plugins.css]]
link = "plugins/fontawesome/font-awesome.min.css"
[[params.plugins.css]]
link = "plugins/hover/hover.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/owl-carousel/owl.carousel.min.css"
[[params.plugins.css]]
link = "plugins/owl-carousel/owl.theme.default.min.css"
[[params.plugins.css]]
link = "plugins/text-animation/text-animation.css"
#[[params.plugins.css]]
#link = "plugins/sztylet/sztylet.css"
#link = "https://fonts.googleapis.com/css?family=Rubik:300,400,500,700,900&display=swap"
#link = "https://fonts.googleapis.com/css2?family=Libre+Baskerville:ital@0;1&display=swap"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/wow.min.js"
[[params.plugins.js]]
link = "plugins/text-animation/text-animation.js"
[[params.plugins.js]]
link = "plugins/jquery.waypoints.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/owl-carousel/owl.carousel.min.js"


############################## navigation ###############################

# main menu
[[menu.main]]
name = "Home"
URL = "#home"
weight = 1

[[menu.main]]
name = "About me"
URL = "#about"
weight = 2

[[menu.main]]
name = "Services"
URL = "#service"
weight = 3

[[menu.main]]
name = "Portfolio"
URL = "#portfolio"
weight = 4

#[[menu.main]]
#name = "Testimonial"
#URL = "#testimonial"
#weight = 5

[[menu.main]]
name = "Contact"
URL = "#contact"
weight = 6


#################### default parameters ################################
[params]
logo_light = "images/logo.png"
logo_dark = "images/logo-dark.png"
# Meta data
description = "Jacek Jonca-Jasinski webpage"
author = "Jacek Jonca-Jasinski"
# contact form action
contact_form_action = "https://formspree.io/moqldnby" # contact form works with https://formspree.io
# Google Analitycs
google_analitycs_id = "UA-5302655-1" # your id

# Preloader
[params.preloader]
enable = false
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.
  
############################# social site ########################
#[[params.social]]
#icon = "fa-facebook-f" # fontawesome icon 4.7.0 : https://fontawesome.com/v4.7.0/icons/
#link = "https://www.facebook.com/somrat.mac"

[[params.social]]
icon = "fa-twitter" # fontawesome icon 4.7.0 : https://fontawesome.com/v4.7.0/icons/
link = "https://twitter.com/joncadotorg"

[[params.social]]
icon = "fa-instagram" # fontawesome icon 4.7.0 : https://fontawesome.com/v4.7.0/icons/
link = "https://www.instagram.com/joncadotorg/"

[[params.social]]
icon = "fa-github" # fontawesome icon 4.7.0 : https://fontawesome.com/v4.7.0/icons/
link = "https://github.com/jacek-jonca"

[[params.social]]
icon = "fa-linkedin" # fontawesome icon 4.7.0 : https://fontawesome.com/v4.7.0/icons/
link = "https://www.linkedin.com/in/jacekjonca/"


################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
# copyright
copyright = "Jacek Jońca-Jasiński"

